### PR TITLE
Routine maintenance 2023-08

### LINKED ISSUE #490: Dependency Dashboard
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Repository problems

These problems occurred while renovating this repository.

 - WARN: Using npm packages for Renovate presets is now deprecated. Please migrate to repository-based presets instead.

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update react monorepo to v18 (major)](../pull/454) (`react`, `react-dom`)
 - [ ] [Update storybook monorepo to v7 (major)](../pull/587) (`@storybook/addon-a11y`, `@storybook/addon-actions`, `@storybook/addon-links`, `@storybook/addon-storysource`, `@storybook/addon-viewport`, `@storybook/addons`, `@storybook/builder-webpack5`, `@storybook/react`)

## Ignored or Blocked

These are blocked by an existing closed PR and will not be recreated unless you click a checkbox below.

 - [ ] [Update dependency @launchpadlab/prettier-config to v2](../pull/598)

## Detected dependencies

<details><summary>github-actions</summary>
<blockquote>

<details><summary>.github/workflows/publish.yml</summary>

 - `actions/checkout v3`
 - `actions/setup-node v3`

</details>

</blockquote>
</details>

<details><summary>npm</summary>
<blockquote>

<details><summary>package.json</summary>

 - `classnames ^2.3.1`
 - `cleave.js ^1.6.0`
 - `date-fns ^2.28.0`
 - `filter-invalid-dom-props ^3.0.1`
 - `lodash ^4.17.21`
 - `prop-types ^15.8.1`
 - `react-color ^2.19.3`
 - `react-datepicker ^4.8.0`
 - `react-modal ^3.14.4`
 - `react-outside-click-handler ^1.3.0`
 - `react-switch ^7.0.0`
 - `redux-flash ^2.0.2`
 - `@babel/cli ^7.17.6`
 - `@babel/core ^7.17.9`
 - `@launchpadlab/babel-preset ^2.1.1`
 - `@launchpadlab/eslint-config ^3.0.1`
 - `@launchpadlab/prettier-config ^1.0.0`
 - `@size-limit/preset-small-lib ^8.2.6`
 - `@storybook/addon-a11y ^6.4.22`
 - `@storybook/addon-actions ^6.4.22`
 - `@storybook/addon-links ^6.4.22`
 - `@storybook/addon-storysource ^6.4.22`
 - `@storybook/addon-viewport ^6.4.22`
 - `@storybook/addons ^6.4.22`
 - `@storybook/builder-webpack5 ^6.5.14`
 - `@storybook/manager-webpack5 ^6.5.14`
 - `@storybook/react ^6.4.22`
 - `@wojtekmaj/enzyme-adapter-react-17 ^0.8.0`
 - `babel-loader ^9.1.0`
 - `bourbon ^7.2.0`
 - `bourbon-neat ^4.0.0`
 - `core-js ^3.21.1`
 - `css-loader ^6.7.2`
 - `documentation ^14.0.2`
 - `enzyme ^3.2.0`
 - `eslint ^8.46.0`
 - `husky ^8.0.3`
 - `jest ^29.6.2`
 - `jest-canvas-mock ^2.1.1`
 - `jest-environment-jsdom ^29.6.2`
 - `lint-staged ^14.0.1`
 - `prettier ^3.0.0`
 - `react ^17.0.0`
 - `react-dom ^17.0.0`
 - `redux ^4.1.2`
 - `regenerator-runtime ^0.14.0`
 - `sass ^1.56.1`
 - `sass-loader ^13.2.0`
 - `size-limit ^8.2.6`
 - `style-loader ^3.3.1`
 - `webpack ^5.75.0`
 - `react ^16.14.0 || ^17.0.0`
 - `node ^18.12`

</details>

</blockquote>
</details>

<details><summary>nvm</summary>
<blockquote>

<details><summary>.nvmrc</summary>

 - `node v18.12.1`

</details>

</blockquote>
</details>

---

- [ ] Check this box to trigger a request for Renovate to run again on this repository

### LINKED ISSUE #570: Upgrade Jest to v28

### LINKED ISSUE #597: Console warning about duplicate manual mock
## Environment

- `@launchpad/lp-components` version: 8.1.0
- `react` version: 17
- `node` version: 18

## Expected Behavior
No warnings show when running `yarn jest`

## Current Behavior
We see a warning about duplicate manual mocks found

## Steps to Reproduce
- Run `yarn test`

## Suggested Solution
Not sure! Needs investigation. The cloudinary mock **shouldn't** be included in `lib` (the build output), so it's likely a configuration issue

### PR DESCRIPTION
**Pull request by chawes13**
- Resolves #570 
- Resolves #490 (except for libraries mentioned out of scope below)
- Resolves #597 

## QA
- [x] `yarn lint` runs with 0 warnings and 0 errors
- [x] Storybook styles are parity with http://lp-components.herokuapp.com/

## Out of Scope
- Upgrading storybook (see #594)
- Upgrading to React 18 (see #567 and #568)

## Author Checklist

- [x] Add unit test(s)
- [x] Update version in package.json (see the [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/main/gists/npm-package-guidelines.md#pull-requests-and-deployments))
- [x] Update documentation (if necessary)
- [ ] Add story to storybook (if necessary)
- [x] Assign dev reviewer

### CODE REVIEW

File: src/controls/color-picker.js [hunk 1]
```diff
@@ -35,46 +36,60 @@ const propTypes = {
...
     <div className="color-picker">
-      <span
-        className="swatch"
-        style={{ background: value || 'black' }}
-        onClick={() => {
-          toggleExpanded()
-          return onOpen()
+      <OutsideClickHandler
+        onOutsideClick={(e) => {
+          if (containerRef && containerRef.current.contains(e.target)) {
```
Comment (chawes13) [inline src/controls/color-picker.js:66]: This allows the `ColorInput` to define its own target area for what it considers to be "outside". When clicking on the input, we want the chrome picker to stay open, as opposed to getting closed by `toggleExpanded(false)`

File: src/controls/paginator/page-link.js [hunk 2]
```diff
@@ -22,8 +22,9 @@ function PageLink({ className, active, onClick, children, ...rest }) {
   return (
     <li className={classnames(className, { active: active })}>
       <a
+        role="link"
         onClick={onClick}
-        onKeyPress={triggerOnKeys(onClick, ENTER_KEY_CODE)} // keyboard interaction requirement
+        onKeyDown={triggerOnKeys(onClick, ENTER_KEY_CODE)} // keyboard interaction requirement
```
Comment (chawes13) [inline src/controls/paginator/page-link.js:27]: https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event

File: src/controls/paginator/page-link.js [hunk 3]
```diff
@@ -22,8 +22,9 @@ function PageLink({ className, active, onClick, children, ...rest }) {
   return (
     <li className={classnames(className, { active: active })}>
       <a
+        role="link"
```
Comment (chawes13) [inline src/controls/paginator/page-link.js:25]: Allows us to keep these as links which is nice for having them show up in the screenreader "Links" menu

File: src/controls/tab-bar/tab-bar.js [hunk 4]
```diff
@@ -87,20 +81,18 @@ function TabBar({
             role="presentation"
             onKeyDown={(e) => manageFocus(e, { vertical })}
           >
-            <a
+            <button
```
Comment (chawes13) [inline src/controls/tab-bar/tab-bar.js:84]: Flagged by the `jsx-a11y` plugin from upgrading lpl's eslint-config

File: src/forms/helpers/dropdown-select.js [hunk 5]
```diff
@@ -23,9 +23,13 @@ function DropdownSelect({ children, className, selectedValues }) {
   return (
     <OutsideClickHandler onOutsideClick={() => toggleExpanded(false)}>
       <div className="dropdown-select">
-        <div className="select-input" onClick={() => toggleExpanded()}>
+        <button
```
Comment (chawes13) [inline src/forms/helpers/dropdown-select.js:26]: Flagged by the `jsx-a11y` plugin from upgrading lpl's eslint-config

File: src/forms/helpers/omit-label-props.js [hunk 6]
```diff
@@ -10,6 +10,8 @@ import { omit } from '../../utils'
  * - `tooltip`
  * - `label`
  * - `requiredIndicator`
+ * - `errorComponent`
+ * - `labelComponent`
```
Comment (chawes13) [inline src/forms/helpers/omit-label-props.js:14]: Noticed these were missing from the docs

File: src/forms/inputs/checkbox-group.js [hunk 7]
```diff
@@ -109,7 +109,9 @@ function CheckboxGroup(props) {
     className,
     checkboxInputProps,
     ...rest
-  } = omitLabelProps(props)
+  } = props
+  const inputProps = omitLabelProps(rest)
```
Comment (chawes13) [inline src/forms/inputs/checkbox-group.js:113]: This is pretty wild. We got a _lot_ of `react/no-unused-prop-types` warnings when we upgraded to the last eslint v7 (even before v8). It looks like there was an issue with the implementation, because on `main` it doesn't work as you'd expect it to:


`eslint` is not able to determine if the destructured props resulting from `omitLabelProps` are actually the props that you intended on using – fair enough. Just took a little bit of restructuring, which you'll see repeated across several components

File: src/forms/inputs/checkbox.js [hunk 8]
```diff
@@ -42,7 +42,7 @@ import {
 
 const propTypes = {
   ...fieldPropTypesWithValue(PropTypes.bool),
-  label: PropTypes.node,
+  label: PropTypes.node, // eslint-disable-line react/no-unused-prop-types
```
Comment (chawes13) [inline src/forms/inputs/checkbox.js:45]: We know this is passed straight down to LabeledField on line 56

File: src/forms/inputs/file-input/file-input.js [hunk 9]
```diff
@@ -64,8 +64,8 @@ const propTypes = {
   thumbnail: PropTypes.string,
   hidePreview: PropTypes.bool,
   className: PropTypes.string,
-  previewComponent: PropTypes.func,
-  children: PropTypes.node,
+  previewComponent: PropTypes.func, // eslint-disable-line react/no-unused-prop-types
+  children: PropTypes.node, // eslint-disable-line react/no-unused-prop-types
```
Comment (chawes13) [inline src/forms/inputs/file-input/file-input.js:68]: We know these are being used by the RenderPreview component

File: src/forms/inputs/file-input/file-input.js [hunk 10]
```diff
@@ -147,7 +148,7 @@ function FileInput(props) {
     const { value, onChange } = input
     const valueToUpdate = value.slice(0, 1)
     onChange(valueToUpdate)
-  }, [multiple])
+  }, [multiple, prevMultiple, input])
```
Comment (chawes13) [inline src/forms/inputs/file-input/file-input.js:151]: Flagged by `react-hooks/exhaustive-deps`

File: src/forms/inputs/file-input/image-preview.js [hunk 11]
```diff
@@ -14,7 +14,7 @@ const defaultProps = {
 function ImagePreview({ image }) {
   return (
     <div className="thumbnail">
-      <img src={image} />
+      <img src={image} alt="" />
```
Comment (chawes13) [inline src/forms/inputs/file-input/image-preview.js:17]: Flagged by `jsx-a11y`

File: src/forms/inputs/switch.js [hunk 12]
```diff
@@ -44,7 +44,7 @@ import { compose, generateInputErrorId } from '../../utils'
 
 const propTypes = {
   ...fieldPropTypesWithValue(PropTypes.bool),
-  label: PropTypes.node,
+  label: PropTypes.node, // eslint-disable-line react/no-unused-prop-types
```
Comment (chawes13) [inline src/forms/inputs/switch.js:47]: We know this is getting passed to LabeledField

File: src/forms/labels/input-label.js [hunk 13]
```diff
@@ -106,7 +106,8 @@ function InputLabel({
         </label>
       )}
       {tooltip && (
-        <span
+        <button
+          type="button"
```
Comment (chawes13) [inline src/forms/labels/input-label.js:110]: Ideally, I'd like to remove this altogether since there are much better tooltip implementations out there but I'm considering that out of scope for this change

File: test/controls/tab-bar.test.js [hunk 14]
```diff
@@ -96,20 +96,22 @@ test('Inactive tabs are explicitly removed from the natural tab order', () => {
   ).toBe(true)
 })
 
-test('Tab to show is triggered via Enter', () => {
+// Enzyme's simulate doesn't translate keyboard events to click events. This test can be re-enabled after the switch to RTL
```
Comment (chawes13) [inline test/controls/tab-bar.test.js:99]: Comment says it all

**Comment by chawes13** [comment]
@bhennes2 I didn't originally intend for this to be a breaking change, but once I upgraded to our latest eslint configuration there were a few `jsx-a11y` errors that I couldn't ignore. Overall the changes are all styling based on probably don't affect too many projects (if any)!

File: test/controls/color-picker.test.js [hunk 15]
```diff
@@ -11,14 +11,6 @@ test('ColorPicker toggles expanded when swatch is clicked', () => {
   expect(wrapper.find('.popover').exists()).toBe(false)
 })
 
-test('ColorPicker collapses when background is clicked', () => {
-  const wrapper = mount(<ColorPicker />)
-  wrapper.find('.swatch').simulate('click')
-  expect(wrapper.find('.popover').exists()).toBe(true)
-  wrapper.find('.cover').simulate('click')
-  expect(wrapper.find('.popover').exists()).toBe(false)
-})
```
Comment (chawes13) [inline test/controls/color-picker.test.js:20]: Enzyme's `click` simulation doesn't trigger the `OnOutsideClick` component's logic. I'm _ok_ with that, given that we're using a third party library which has its own test coverage

File: src/controls/tab-bar/tab-bar.js [hunk 16]
```diff
@@ -87,20 +81,18 @@ function TabBar({
...
+              type="button"
               id={'tab-' + toLower(optionValue)} // allow sections to reference tab using `aria-labelledby`
               onClick={() => {
                 onChange(optionValue)
               }}
-              onKeyPress={triggerOnKeys(() => {
```
Comment (bhennes2) [inline src/controls/tab-bar/tab-bar.js:95]: With this being an HTML `<button>` now, are the keyboard commands out-of-the-box? (so this can be removed)

File: test/controls/tab-bar.test.js [hunk 17]
```diff
@@ -96,20 +96,22 @@ test('Inactive tabs are explicitly removed from the natural tab order', () => {
...
 
-test('Tab to show is triggered via Space', () => {
+// Enzyme's simulate doesn't translate keyboard events to click events. This test can be re-enabled after the switch to RTL
+test.skip('Tab to show is triggered via Space', () => {
   const onChange = jest.fn()
   const wrapper = mount(
     <TabBar options={objectOptions} value="home" onChange={onChange} />
   )
-  wrapper.find('li > a').first().simulate('keyPress', { keyCode: 32 })
+  wrapper.find('[role="tab"]').first().simulate('keyPress', { keyCode: 32 })
```
Comment (bhennes2) [inline test/controls/tab-bar.test.js:115]: Out of curiosity, is there a `{ key: 'Space'}` option similar to what you did for `Enter` above?

File: src/forms/inputs/checkbox-group.js (hunk 7 above)
Comment (bhennes2) [reply src/forms/inputs/checkbox-group.js:113]: 🤔 I would have expected `const inputProps = omitLabelProps(rest)` to pass in `props` instead of `rest` for `omitLabelProps`. Can you provide a bit more details on that change?

Comment (bhennes2) [reply src/forms/inputs/checkbox-group.js:113]: Is `rest` here `props` without the `input, meta, options, className, checkboxInputProps` keys?

**Review by bhennes2 — COMMENTED** [review]
Overall looking good - have a few follow up questions on the `omitLabelProps` changes just the make sure I'm understanding the diff between `props` and `rest`.

File: src/controls/tab-bar/tab-bar.js (hunk 16 above)
Comment (chawes13) [reply src/controls/tab-bar/tab-bar.js:95]: Yep, exactly! Trust the platform 🤩

File: test/controls/tab-bar.test.js (hunk 17 above)
Comment (chawes13) [reply test/controls/tab-bar.test.js:115]: Hmm, maybe? I'm not keen on spending much time on that since we're removing Enzyme in #586

File: src/forms/inputs/checkbox-group.js (hunk 7 above)
Comment (chawes13) [reply src/forms/inputs/checkbox-group.js:113]: If we were to store `omitLabelProps(props)` in the `inputProps` variable, then that variable would include `input, meta, options, className, checkboxInputProps`, which would then get passed _directly_ to the input (which we don't want to happen).

We don't _need_ to call `omitLabelProps(props)` when destructuring those keys because we aren't destructuring any of the label props in the first place!

To illustrate:
```js
const props = { label: 'First Name', input: { name: 'firstName', value: 'Conor', onChange: setFirstName }, 'aria-label': 'Employee First Name' }
const { input, ...rest } = props // rest -> { label: 'First Name', 'aria-label': 'Employee First Name' }
const inputProps = omitLabelProps(rest) // inputProps -> { 'aria-label': 'Employee First Name' }
```
Before, we were technically doing this all in one step, which confused the linter
```js
const props = { label: 'First Name', input: { name: 'firstName', value: 'Conor', onChange: setFirstName }, 'aria-label': 'Employee First Name' }
const { input, ...rest } = omitLabelProps(props) // rest -> { 'aria-label': 'Employee First Name' }
```

File: test/controls/tab-bar.test.js (hunk 17 above)
Comment (bhennes2) [reply test/controls/tab-bar.test.js:115]: Sounds good! Was a minor comment regardless.

File: src/forms/inputs/checkbox-group.js (hunk 7 above)
Comment (bhennes2) [reply src/forms/inputs/checkbox-group.js:113]: Confused the linter and me 😉 

I follow now - I thought in addition to making the linter happy this might actually introduce a _slight_ difference in functionality in which `prop` keys are filtered but I understand the equivalence now. Thank you!

**Review by bhennes2 — APPROVED** [review]
I believe we cleared up my remaining questions so going to re-review and approve!
